# Model arguments
model_name_or_path: pbevan11/Mistral-Nemo-Instruct-MCAI-SFT
torch_dtype: null

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  pbevan11/multilingual-constitutional-preference-pairs: 0.2
  pbevan11/ultrafeedback_binarized_multilingual: 0.09
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
beta: 0.1
do_eval: true
do_train: true
eval_strategy: steps
eval_steps: 1000
gradient_accumulation_steps: 1
gradient_checkpointing: true
hub_model_id: MMistral-Nemo-Instruct-MCAI-SFT-DPO
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: linear
max_length: 1024
max_prompt_length: 512
num_train_epochs: 1
optim: rmsprop
output_dir: models/Mistral-Nemo-Instruct-MCAI-SFT-DPO
per_device_train_batch_size: 6
per_device_eval_batch_size: 8
push_to_hub: true
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
seed: 42
warmup_ratio: 0.1
report_to:
  - wandb